project:
  type: book
  resources:
  - "data/*"

book:
  title: "Zbiór zadań - Python"
  author: Piotr Jastrzębski
  date: today
  cover-image: pop.jpg
  chapters:
    - index.qmd
    - part: "Wprowadzenie do języka Python"
      chapters: 
        - wejsciewyjscie.qmd
        - listy.qmd
        - krotki.qmd
        - slowniki.qmd
        - argumenty_funkcji.qmd
        - fstringi.qmd
    - part: "Programowanie obiektowe"
      chapters:
        - inicjalizator.qmd
        - wlasciwosci.qmd
        - dziedziczenie_polimorfizm.qmd
        - repr_str.qmd
        - kontenery.qmd
        - emulacja_arytmetyki.qmd
        - emulacja_porownania.qmd
    - part: "Zaawansowane zagadnienia"
      chapters:
        - dekoratory.qmd
        - re.qmd
        - iteratory_generatory.qmd
        - operatory_bitowe.qmd
  downloads: [pdf, epub]
  repo-url: https://github.com/pjastr/zbior-zadan-python
  repo-actions: [issue]


execute:
  freeze: auto

format:
  html:
    theme:
      light: cosmo
      dark: solar
    lang: pl
  pdf:
    lang: pl
    header-includes: |
      \titlehead{\includegraphics[width=6in]{pop.jpg}}
  epub:
    lang: pl
    cover-image: pop.jpg
    toc: true


